#!/usr/bin/perl
# vim: ts=4 sw=4 nowrap

# Generate a report of the release-critical bugs for packages

use Getopt::Std;
require scanlib;
require bugcfg;
use strict;
use warnings;

my $Version		= "BugReport 1.4\nCopyright (C) 1998-2002 Wichert Akkerman <wakkerma\@debian.org>\n";
my $html		= 0;
my $statusfile		= "status";
my $commentsfile	= "comments";
my $NMUfile		= "/debian/home/doogie/public_html/incoming/bugs_closed";
$NMUfile		= "/debian/home/doogie/chgscan/db/bugs_closed"; # Changed as of request by dark  -Joey, 99/11/22
$NMUfile		= "http://auric.debian.org/~doogie/incoming/bugs_closed"; # Changed as of request by dark  -Joey, 99/11/22

sub ShowVersion() {
	print "$Version\n";
	exit 0;
}

sub ShowUsage() {
	print <<EOF;
Usage:
  $0 [-V] [-h] [-H] [-l] [-s] [-d distrib] [-S file] [-C file]
Options:
  -V    show version
  -h    show some (hopefully) helpful information
  -H    produce HTML output
  -l    list all release-critical bugs
  -s    list bug statistics
  -t    show bugs relevant for testing only
  -d    only list these distributions (comma-separated)
  -S    use different statusfile
  -C    use different commentsfile
EOF
	exit 0;
}

sub PrintPackageHeader() {
	my $p	= shift;	# Package to print
	my ($name, $email);	# Name & email of maintainer

	if ($html) {
	    print "<div class=\"package\"><pre>";
		print "<a name=\"$p\"><strong>Package:</strong></a> " . &wwwname($p);
		print " ($scanlib::section{$p}).\n";
		print "<strong>Maintainer:</strong> ";
		if (defined($scanlib::maintainer{$p})) {
			$_ = $scanlib::maintainer{$p};
			($name,$email) = m/(.*) <([^>]*)>/;
			print "$name &lt;<a href=\"http://bugs.debian.org/$email\">$email</A>&gt;\n";
		} else {
			print "unknown\n";
		}
	} else {
		print "\nPackage: $p ($scanlib::section{$p})\n";
		print "Maintainer: " . (defined($scanlib::maintainer{$p}) ? $scanlib::maintainer{$p} : "unknown") . "\n";
	}
}

sub PrintPackageFooter() {
	my $p	= shift;	# Package to print

	if ($html) {
		print "</pre></div>\n";
	}
}

sub MakeBuglist() {
	my $p;				# Index variable
	my $nr;			# Current bugnumber
	my $sect;			# BTS-subsection for bugnumber
	my $header;		# Flag if packagename has already been printed
	my $fontset;		# Did we change the font?

	for my $p (sort {$a cmp $b} keys %scanlib::packagelist) {
		next if (defined $bugcfg::exclude{$p});
		$header = 0;
		$fontset = 0;
		if (defined $scanlib::comments{$p}) {
			if ($html && defined($scanlib::comments{$p})) {
				if ($scanlib::comments{$p} =~ m/^\[REMOVE\]/) {
					$fontset=1;
					print "<span style=\"color: red\">";
				}
			}
			$header=1;
			&PrintPackageHeader($p);
			print $scanlib::comments{$p};
		}
		for $nr (sort split(/ /, $scanlib::packagelist{$p})) {
			next if (defined $bugcfg::exclude{$nr});
			if (! $header) {
				$header = 1;
				&PrintPackageHeader($p);
			}

			if ($html) {
				my $worry = scanlib::check_worry($scanlib::bugs{$nr});
			
				if ($scanlib::bugs{$nr} =~ m/ \[[^]]*X/) {
					print '<span style="color: #808080">';
				} elsif ($scanlib::bugs{$nr} =~ m/^\[[^]]*P/) {
					print '<span style="color: #f040d0">';
				} elsif ($scanlib::bugs{$nr} =~ m/^\[[^]]*\+/) {
					print '<span style="color: #00aa00">';
				} elsif ($scanlib::bugs{$nr} =~ m/^\[[^]]*H/) {
					print '<span style="color: #ffaa30">';
				}
				print "<strike>" if ($scanlib::bugs{$nr} =~ m/^\[.......I\]/);
				print "<em class=\"worry\">" if $worry;
				($sect=$nr) =~ s/([0-9]{2}).*/$1/;
				print "<A NAME=\"$nr\"></A>  " . &wwwnumber($nr) . ' ' .
					  htmlsanit($scanlib::bugs{$nr}) . "\n";
				print "</em>" if $worry;
				print "</strike>" if ($scanlib::bugs{$nr} =~ m/^\[.......I\]/);
			} else {
				printf("  %-6d %s\n", $nr, $scanlib::bugs{$nr});
			}
			print $scanlib::comments{$nr} if (defined($scanlib::comments{$nr}));
			print "[FIX] Fixed by package " . $scanlib::NMU{$nr, "source"} . ", version " . $scanlib::NMU{$nr, "version"} . " in Incoming\n" if (defined $scanlib::NMU{$nr});
			print "</span>" if ($html && ($scanlib::bugs{$nr} =~ m/^\[[^]]*[H+P]/ ||
			                              $scanlib::bugs{$nr} =~ m/ \[[^]]*X/));
		}
		print "</span>" if ($fontset);
		if ($header) {
			&PrintPackageFooter($p);
		}
	}
}


sub MakeStatistics() {
	my $bugcount;		# Total number of bugs so far
	my $count;		# Number of bugs for this package
	my $remtotal;		# Total number of bugs for packages marked REMOVE
	my $patchtotal;		# Total number of bugs marked patch
	my $pendingtotal;	# Total number of bugs marked pending
	my $ignoretotal;	# Total number of bugs marked ignore
	my $nottestingtotal;	# Total number of bugs on packages not in testing
	my $worrytotal;		# Total number of bugs we're actually worried about
	my $p;			# Index variable
	my %list;		# List of bugnumber associated with package

	$bugcount=0;
	for my $p (sort keys %scanlib::packagelist) {
		next if (defined $scanlib::exclude{$p});
		$count=0;
		for my $nr (split(/ /, $scanlib::packagelist{$p})) {
			$pendingtotal++ if ($scanlib::bugs{$nr} =~ m/^\[[^]]*P/);
			$patchtotal++ if ($scanlib::bugs{$nr} =~ m/^\[[^]]*\+/);
			$ignoretotal++ if ($scanlib::bugs{$nr} =~ m/^\[[^]]*I/);
			$nottestingtotal++ if ($scanlib::bugs{$nr} =~ m/ \[[^]]*X/);
			$worrytotal++ unless (
				$scanlib::bugs{$nr} =~ m/^\[[^]]*I/ or
				$scanlib::bugs{$nr} =~ m/ \[[^]]*X/ or
				($scanlib::bugs{$nr} =~ m/ \[[^]]*[OSUE]/ and $scanlib::bugs{$nr} !~ m/ \[[^]]*T/));

			if (not defined($scanlib::exclude{$nr})) {
				$bugcount++;
				$count++;
			} 
		}
		$remtotal+=$count if (defined($scanlib::comments{$p}) && $scanlib::comments{$p} =~ m/^\[REMOVE\]/);
	}

	if ($html) {
		print "<strong>Total number of release-critical bugs:</strong> $bugcount<BR>\n";
		printf("<strong>Number that will disappear after removing packages marked [REMOVE]:</strong> %d<BR>\n", $remtotal);
		printf("<strong>Number that have a patch:</strong> %d<BR>\n", $patchtotal);
		printf("<strong>Number that have a fix prepared and waiting to upload:</strong> %d<BR>\n", $pendingtotal);
		printf("<strong>Number that are being ignored:</strong> %d<BR>\n", $ignoretotal);
		printf("<strong>Number on packages not in testing:</strong> %d<BR>\n", $nottestingtotal);
		printf("<strong>Number concerning the next release (excluding ignored and not-in-testing):</strong> %d<P>\n", $worrytotal);
	} else {
		print "Total number of release-critical bugs: $bugcount\n";
		printf("Number that will disappear after removing packages marked [REMOVE]: %d\n", $remtotal);
		printf("Number that have a patch: %d\n", $patchtotal);
		printf("Number that have a fix prepared and waiting to upload: %d\n", $pendingtotal);
		printf("Number that are being ignored: %d\n", $ignoretotal);
		printf("Number on packages not in testing: %d\n", $nottestingtotal);
		printf("Number concerning the next release (excluding ignored and not-in-testing): %d\n", $worrytotal);
	}
}


sub FilterPackages() {
	my $filter = shift;		# Distribution we want to keep

	for my $p (sort keys %scanlib::packagelist) {
		delete $scanlib::packagelist{$p} unless ($scanlib::section{$p} =~ m/^$filter/);
	}
}

sub FilterBugs() {
	for my $p (sort keys %scanlib::packagelist) {
		$scanlib::packagelist{$p} = join(' ', grep { check_worry($scanlib::bugs{$_}) } split / /, $scanlib::packagelist{$p});
		delete $scanlib::packagelist{$p} if ($scanlib::packagelist{$p} eq '');
	}
}

my ($opt_h,$opt_V,$opt_S,$opt_C,$opt_H,$opt_d,$opt_t,$opt_s,$opt_l);

getopts('VhHlstd:S:C:');
ShowUsage if ($opt_h);
ShowVersion if ($opt_V);
$statusfile=$opt_S if ($opt_S);
$commentsfile=$opt_C if ($opt_C);
$html=1 if ($opt_H);

scanlib::readstatus($statusfile);
scanlib::readcomments($commentsfile);
# scanlib::readNMUstatus($NMUfile);

&FilterPackages($opt_d) if ($opt_d);
&FilterBugs() if ($opt_t);

MakeStatistics if ($opt_s);
if ($opt_l) {
	MakeBuglist 
}

exit 0;

