#! /usr/bin/perl

require bugcfg;
require scanlib;
use strict;
# use warnings;

# Main part

scanlib::readpackages($bugcfg::debian_ftproot, "debian") if defined $bugcfg::debian_ftproot;
scanlib::readsources($bugcfg::debian_ftproot, "debian")  if defined $bugcfg::debian_ftproot;

scanlib::readdebbugssources($bugcfg::debian_sources, "debian") if defined $bugcfg::debian_sources;


scanlib::readpseudopackages();
scanlib::readmaintainers();
scanlib::scanspool();

for my $p (keys %scanlib::packagelist) {
	my $section;
	if (exists $scanlib::section{$p}) {
	    $section = $scanlib::section{$p};
	} else {
	    $section = $scanlib::debbugssection{$p};
	}
	print "package\n";
	print $p, "\n";
	print $section, "\n";
	print $scanlib::maintainer{$p}, "\n";
	print "\n";
}

for my $b (keys %scanlib::bugs) {
	print "bug\n";
	for my $key (keys %{$scanlib::bugs{$b}}) {
		print $key, "=", $scanlib::bugs{$b}->{$key}, "\n";
	}
	print "\n";
}

print "end\n";

exit 0;

