#! /usr/bin/perl

require bugcfg;
require scanlib;
use strict;
use warnings;

# Main part

scanlib::readpackages($bugcfg::debian_ftproot, "debian") if defined $bugcfg::debian_ftproot;
scanlib::readpackages($bugcfg::nonUS_ftproot, "non-US")  if defined $bugcfg::nonUS_ftproot;
scanlib::readsources($bugcfg::debian_ftproot, "debian")  if defined $bugcfg::debian_ftproot;
scanlib::readsources($bugcfg::nonUS_ftproot, "non-US")   if defined $bugcfg::nonUS_ftproot;

scanlib::readdebbugssources($bugcfg::debian_sources, "debian") if defined $bugcfg::debian_sources;
scanlib::readdebbugssources($bugcfg::nonUS_sources, "non-US") if defined $bugcfg::nonUS_sources;


scanlib::readpseudopackages();
scanlib::readmaintainers();
scanlib::scanspool();

for my $p (keys %scanlib::packagelist) {
	my $section;
	if (exists $scanlib::section{$p}) {
	    $section = $scanlib::section{$p};
	} else {
	    $section = $scanlib::debbugssection{$p};
	}
	print "$p $section $scanlib::maintainer{$p}\n";
	for my $b (@{$scanlib::packagelist{$p}}) {
		print "$scanlib::bugs{$b}\n";
	}
	print "\n";
}

exit 0;

