#! /bin/sh

set -e

cd /org/bugs.debian.org/bugscan

tempdir=`mktemp -d`

find counts -type f -not -iname '*.bad'| sort | xargs grep '^' /dev/null |
    sed 's/^.*count-//;s/ .*$//;s/:/ /' >"$tempdir/rc_bugs_total"
find counts -type f -not -iname '*.bad'| sort | xargs egrep '^(.* ){6}' /dev/null | tr ":-" " " |
    cut -d" " -f2,9 >"$tempdir/rc_bugs_next_release"
find counts -type f -not -iname '*.bad'| sort | xargs egrep '^(.* ){7}' /dev/null | tr ":-" " " |
    cut -d" " -f2,10 >"$tempdir/rc_bugs_current_release"

# This is the date of the bullseye release
previous_release="202108140000"

# And this is a month ago
previous_month=`date +"%Y%m%d%H%M" --date="1 month ago"`

cat <<EOF | gnuplot
set xdata time
set timefmt "%Y%m%d%H%M"
set format x "%m\n%Y"
set title "Number of release-critical bugs"
set nokey
set terminal png
set yrange [0:]
#set xtics 2678400
#set nomxtics
# release critical bugs
set linetype  1 lc rgb "dark-violet" lw 1
# RC bugs next release
set linetype  2 lc rgb "#009e73" lw 1
# RC bugs current release
set linetype  3 lc rgb "#56b4e9" lw 1
set linetype  4 lc rgb "#e69f00" lw 1
set linetype  5 lc rgb "#f0e442" lw 1
set linetype  6 lc rgb "#0072b2" lw 1
set linetype  7 lc rgb "#e51e10" lw 1
set linetype  8 lc rgb "black"   lw 1
set linetype  9 lc rgb "gray50"  lw 1
set linetype cycle  9
set output "/srv/bugs.debian.org/www/bugscan/graph.png"
plot "$tempdir/rc_bugs_total" using 1:2 with lines, "$tempdir/rc_bugs_next_release" using 1:2 with lines, "$tempdir/rc_bugs_current_release" using 1:2 with lines
set xrange ["$previous_release":]
set output "/srv/bugs.debian.org/www/bugscan/graph-release.png"
plot "$tempdir/rc_bugs_total" using 1:2 with lines, "$tempdir/rc_bugs_next_release" using 1:2 with lines, "$tempdir/rc_bugs_current_release" using 1:2 with lines
set xrange ["$previous_month":]
set format x "%d\n%m\n%Y"
set output "/srv/bugs.debian.org/www/bugscan/graph-month.png"
plot "$tempdir/rc_bugs_total" using 1:2 with lines, "$tempdir/rc_bugs_next_release" using 1:2 with lines, "$tempdir/rc_bugs_current_release" using 1:2 with lines
quit
EOF

rm -rf "$tempdir"
