#! /bin/sh

htmldir=/home/sesse/bugscan/www

realmakepage() {
	local	filter="$1"	# Distributions to list
	local	title="$2"	# Title of page
	local	date="$3"	# Date
	local	worry="$4"	# Worry about testing only?
	local	descr		# Description of filter

	if [ -z "$filter" ]; then
		descr="all"
	else
		descr="$filter"
		filter="-d $filter"
	fi

	filter="$filter $worry"

	cat <<EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>$title, $date</title>
  </head>
<body bgcolor="white">
<h1 align="center">$title</h1>

<h2 align="center">$date</h2>

<p align="center">for distribution(s): $descr</p>

<hr>

<p>
EOF
	./bugreport -H -s $filter
	
	cat <<EOF
<p>
Explanation for <a href="http://www.debian.org/Bugs/Developer#tags">bug
tags</a>:

<ul>
   <li><strong>P</strong>: pending</li>
   <li><strong>+</strong>: patch</li>
   <li><strong>H</strong>: help</li>
   <li><strong>M</strong>: moreinfo</li>
   <li><strong>R</strong>: unreproducible</li>
   <li><strong>S</strong>: security</li>
   <li><strong>U</strong>: upstream</li>
   <li><strong>I</strong>: etch-ignore</li>
</ul>

<p>
The second set of tags indicate what releases a bug applies to:
O for oldstable (woody), S for stable (sarge), T for testing (etch),
U for unstable (sid) or E for experimental. X indicates that the
package is not in testing.

<p>

EOF
	./bugreport -H -l $filter

	cat <<EOF
<hr>
This page is automatically generated.<br>
Please contact
<a href="mailto:owner@bugs.debian.org">owner@bugs.debian.org</a> for comments.
</body>
</html>
EOF
}

makemainpage() {
	cat <<EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>$title, $time</title>
  </head>
<body bgcolor="white">
<h1 align="center">$title</h1>

<h2 align="center">$time</h2>

<p align="center">
EOF

	./bugreport -Hs

	cat <<EOF
</p>

<div align="center"><img src="graph.png" alt="Graph of RC bugs"></div>
