#! /bin/sh

newtime=`stat --format %y pstatus | cut -d: -f-2`
oldtime=`stat --format %y pstatus-old | cut -d: -f-2`
title="Bug stamp-out list for $newtime (CST)"
cat <<EOF
$title

EOF
./bugreport -s 

cat <<EOF

Explanation for bug tags:

   P  pending
   +  patch
   H  help
   M  moreinfo
   R  unreproducible
   S  security
   U  upstream
   I  etch-ignore

The second set of tags indicate what releases a bug applies to:
O for oldstable (woody), S for stable (sarge), T for testing (etch),
U for unstable (sid) or E for experimental.

------------------------------------------------------------------------------
EOF

./bugreport -l -S pstatus


